


/**
 * @file
 *
 * @author Generated by LibBi
 * $Rev$
 * $Date$
 */
#ifdef ENABLE_GPERFTOOLS
#include "google/profiler.h"
#endif
#include "bi/init.hpp"
#include "bi/cuda/cuda.hpp"
#include "bi/mpi/mpi.hpp"

#include "sample_cpu.cpp"
