





/**
 * @file
 *
 * @author Generated by LibBi
 * $Rev$
 * $Date$
 */
#ifndef LIBBI_VAR11_HPP
#define LIBBI_VAR11_HPP

#include "bi/model/Var.hpp"
#include "bi/cuda/cuda.hpp"
#include "bi/math/scalar.hpp"


#include "VarCoord11.hpp"

/**
 * Variable: 11.
 */
class Var11 : public bi::Var {
public:
  /**
   * Coordinate type.
   */
  typedef VarCoord11 coord_type;

  /**
   * Constructor.
   */
  Var11();

  /**
   * Get name of the variable.
   *
   * @return Name of the variable.
   */
  static const char* getName();

  /**
   * Get the name used for the variable in input files.
   *
   * @return Input name of the variable.
   */
  static const char* getInputName();

  /**
   * Get the name used for the variable in output files.
   *
   * @return Output name of the variable.
   */
  static const char* getOutputName();

  /**
   * Should the variable be included in input files?
   */
  static bool hasInput();

  /**
   * Should the variable be included in output files?
   */
  static bool hasOutput();
  
  /**
   * Should the variable be output only once, not at every time?
   */
  static bool getOutputOnce();

  /**
   * Initialise dimensions. Called by Model::addVar() after construction.
   *
   * @tparam B Model type.
   *
   * @param m Model.
   */
  template<class B>
  void initDims(const B& m);
    
  /**
   * Id.
   */
  static const int ID = 1;

  /**
   * Size.
   */
  static const int START = 1;
  
  /**
   * Size.
   */
  static const int SIZE = 1;

  /**
   * Number of dimensions.
   */
  static const int NUM_DIMS = 0;
  
  
  
  /**
   * Type.
   */
  static const bi::VarType TYPE = bi::  P_VAR;
};

inline Var11::Var11() : bi::Var(*this) {
  //
}

inline const char* Var11::getName() {
  return "p_R0";
}

inline const char* Var11::getInputName() {
  return "p_R0";
}

inline const char* Var11::getOutputName() {
  return "p_R0";
}

inline bool Var11::hasInput() {
  return BI_REAL(1);
}

inline bool Var11::hasOutput() {
  return BI_REAL(1);
}

inline bool Var11::getOutputOnce() {
  return 1;
}

template<class B>
inline void Var11::initDims(const B& m) {
}

#endif
