





/**
 * @file
 *
 * @author Generated by LibBi
 * $Rev$
 * $Date$
 */
#ifndef LIBBI_VARCOORD5_HPP
#define LIBBI_VARCOORD5_HPP

/**
 * Coordinate: 5.
 */
class VarCoord5 {
public:
  /**
   * Default constructor.
   */
  CUDA_FUNC_BOTH VarCoord5();
  
  

  
  /**
   * Construct from serial index.
   *
   * @param ix Serial index.
   */
  CUDA_FUNC_BOTH VarCoord5(const int ix);
  
  
  /**
   * Increment to next coordinate in serial ordering.
   */
  CUDA_FUNC_BOTH void inc();
   
  /**
   * Decrement to previous coordinate in serial ordering.
   */
  CUDA_FUNC_BOTH void dec();

  /**
   * Recover serial index.
   * 
   * @return Serial index for coordinate.
   */
  CUDA_FUNC_BOTH int index() const;
  
  /**
   * Set serial index.
   *
   * @param ix Serial index for coordinate.
   *
   * Sets the coordinate to be equivalent to the given serial index.
   */
  CUDA_FUNC_BOTH void setIndex(const int ix);

  /**
   * Prefix increment operator.
   */
  CUDA_FUNC_BOTH VarCoord5& operator++() {
    inc();
    return *this;
  }
  
  /**
   * Postfix increment operator.
   */
  CUDA_FUNC_BOTH VarCoord5 operator++(int) {
    VarCoord5 tmp(*this);
    inc();
    return tmp;
  }
  
  /**
   * Prefix decrement operator.
   */
  CUDA_FUNC_BOTH VarCoord5& operator--() {
    dec();
    return *this;
  }
  
  /**
   * Postfix decrement operator.
   */
  CUDA_FUNC_BOTH VarCoord5 operator--(int) {
    VarCoord5 tmp(*this);
    dec();
    return tmp;
  }

  
  
  
};

inline VarCoord5::VarCoord5() {
}




inline VarCoord5::VarCoord5(const int ix) {
  setIndex(ix);
}


inline void VarCoord5::inc() {
  
  
}

inline void VarCoord5::dec() {
  
  
}

inline int VarCoord5::index() const {
  
  return 0;
  
}

inline void VarCoord5::setIndex(const int ix) {  
}

#endif
