





/**
 * @file
 *
 * @author Generated by LibBi
 * $Rev$
 * $Date$
 */
#ifndef LIBBI_VARCOORD8_HPP
#define LIBBI_VARCOORD8_HPP

/**
 * Coordinate: 8.
 */
class VarCoord8 {
public:
  /**
   * Default constructor.
   */
  CUDA_FUNC_BOTH VarCoord8();
  
  

  
  /**
   * Construct from serial index.
   *
   * @param ix Serial index.
   */
  CUDA_FUNC_BOTH VarCoord8(const int ix);
  
  
  /**
   * Increment to next coordinate in serial ordering.
   */
  CUDA_FUNC_BOTH void inc();
   
  /**
   * Decrement to previous coordinate in serial ordering.
   */
  CUDA_FUNC_BOTH void dec();

  /**
   * Recover serial index.
   * 
   * @return Serial index for coordinate.
   */
  CUDA_FUNC_BOTH int index() const;
  
  /**
   * Set serial index.
   *
   * @param ix Serial index for coordinate.
   *
   * Sets the coordinate to be equivalent to the given serial index.
   */
  CUDA_FUNC_BOTH void setIndex(const int ix);

  /**
   * Prefix increment operator.
   */
  CUDA_FUNC_BOTH VarCoord8& operator++() {
    inc();
    return *this;
  }
  
  /**
   * Postfix increment operator.
   */
  CUDA_FUNC_BOTH VarCoord8 operator++(int) {
    VarCoord8 tmp(*this);
    inc();
    return tmp;
  }
  
  /**
   * Prefix decrement operator.
   */
  CUDA_FUNC_BOTH VarCoord8& operator--() {
    dec();
    return *this;
  }
  
  /**
   * Postfix decrement operator.
   */
  CUDA_FUNC_BOTH VarCoord8 operator--(int) {
    VarCoord8 tmp(*this);
    dec();
    return tmp;
  }

  
  
  
};

inline VarCoord8::VarCoord8() {
}




inline VarCoord8::VarCoord8(const int ix) {
  setIndex(ix);
}


inline void VarCoord8::inc() {
  
  
}

inline void VarCoord8::dec() {
  
  
}

inline int VarCoord8::index() const {
  
  return 0;
  
}

inline void VarCoord8::setIndex(const int ix) {  
}

#endif
