





/**
 * @file
 *
 * @author Generated by LibBi
 * $Rev$
 * $Date$
 */
#ifndef LIBBI_VARCOORD1_HPP
#define LIBBI_VARCOORD1_HPP

/**
 * Coordinate: 1.
 */
class VarCoord1 {
public:
  /**
   * Default constructor.
   */
  CUDA_FUNC_BOTH VarCoord1();
  
  

  
  /**
   * Construct from serial index.
   *
   * @param ix Serial index.
   */
  CUDA_FUNC_BOTH VarCoord1(const int ix);
  
  
  /**
   * Increment to next coordinate in serial ordering.
   */
  CUDA_FUNC_BOTH void inc();
   
  /**
   * Decrement to previous coordinate in serial ordering.
   */
  CUDA_FUNC_BOTH void dec();

  /**
   * Recover serial index.
   * 
   * @return Serial index for coordinate.
   */
  CUDA_FUNC_BOTH int index() const;
  
  /**
   * Set serial index.
   *
   * @param ix Serial index for coordinate.
   *
   * Sets the coordinate to be equivalent to the given serial index.
   */
  CUDA_FUNC_BOTH void setIndex(const int ix);

  /**
   * Prefix increment operator.
   */
  CUDA_FUNC_BOTH VarCoord1& operator++() {
    inc();
    return *this;
  }
  
  /**
   * Postfix increment operator.
   */
  CUDA_FUNC_BOTH VarCoord1 operator++(int) {
    VarCoord1 tmp(*this);
    inc();
    return tmp;
  }
  
  /**
   * Prefix decrement operator.
   */
  CUDA_FUNC_BOTH VarCoord1& operator--() {
    dec();
    return *this;
  }
  
  /**
   * Postfix decrement operator.
   */
  CUDA_FUNC_BOTH VarCoord1 operator--(int) {
    VarCoord1 tmp(*this);
    dec();
    return tmp;
  }

  
  
  
};

inline VarCoord1::VarCoord1() {
}




inline VarCoord1::VarCoord1(const int ix) {
  setIndex(ix);
}


inline void VarCoord1::inc() {
  
  
}

inline void VarCoord1::dec() {
  
  
}

inline int VarCoord1::index() const {
  
  return 0;
  
}

inline void VarCoord1::setIndex(const int ix) {  
}

#endif
