





/**
 * @file
 *
 * @author Generated by LibBi
 * $Rev$
 * $Date$
 */
#ifndef LIBBI_VARCOORD10_HPP
#define LIBBI_VARCOORD10_HPP

/**
 * Coordinate: 10.
 */
class VarCoord10 {
public:
  /**
   * Default constructor.
   */
  CUDA_FUNC_BOTH VarCoord10();
  
  

  
  /**
   * Construct from serial index.
   *
   * @param ix Serial index.
   */
  CUDA_FUNC_BOTH VarCoord10(const int ix);
  
  
  /**
   * Increment to next coordinate in serial ordering.
   */
  CUDA_FUNC_BOTH void inc();
   
  /**
   * Decrement to previous coordinate in serial ordering.
   */
  CUDA_FUNC_BOTH void dec();

  /**
   * Recover serial index.
   * 
   * @return Serial index for coordinate.
   */
  CUDA_FUNC_BOTH int index() const;
  
  /**
   * Set serial index.
   *
   * @param ix Serial index for coordinate.
   *
   * Sets the coordinate to be equivalent to the given serial index.
   */
  CUDA_FUNC_BOTH void setIndex(const int ix);

  /**
   * Prefix increment operator.
   */
  CUDA_FUNC_BOTH VarCoord10& operator++() {
    inc();
    return *this;
  }
  
  /**
   * Postfix increment operator.
   */
  CUDA_FUNC_BOTH VarCoord10 operator++(int) {
    VarCoord10 tmp(*this);
    inc();
    return tmp;
  }
  
  /**
   * Prefix decrement operator.
   */
  CUDA_FUNC_BOTH VarCoord10& operator--() {
    dec();
    return *this;
  }
  
  /**
   * Postfix decrement operator.
   */
  CUDA_FUNC_BOTH VarCoord10 operator--(int) {
    VarCoord10 tmp(*this);
    dec();
    return tmp;
  }

  
  
  
};

inline VarCoord10::VarCoord10() {
}




inline VarCoord10::VarCoord10(const int ix) {
  setIndex(ix);
}


inline void VarCoord10::inc() {
  
  
}

inline void VarCoord10::dec() {
  
  
}

inline int VarCoord10::index() const {
  
  return 0;
  
}

inline void VarCoord10::setIndex(const int ix) {  
}

#endif
