





/**
 * @file
 *
 * @author Generated by LibBi
 * $Rev$
 * $Date$
 */
#ifndef LIBBI_VARCOORD11_HPP
#define LIBBI_VARCOORD11_HPP

/**
 * Coordinate: 11.
 */
class VarCoord11 {
public:
  /**
   * Default constructor.
   */
  CUDA_FUNC_BOTH VarCoord11();
  
  

  
  /**
   * Construct from serial index.
   *
   * @param ix Serial index.
   */
  CUDA_FUNC_BOTH VarCoord11(const int ix);
  
  
  /**
   * Increment to next coordinate in serial ordering.
   */
  CUDA_FUNC_BOTH void inc();
   
  /**
   * Decrement to previous coordinate in serial ordering.
   */
  CUDA_FUNC_BOTH void dec();

  /**
   * Recover serial index.
   * 
   * @return Serial index for coordinate.
   */
  CUDA_FUNC_BOTH int index() const;
  
  /**
   * Set serial index.
   *
   * @param ix Serial index for coordinate.
   *
   * Sets the coordinate to be equivalent to the given serial index.
   */
  CUDA_FUNC_BOTH void setIndex(const int ix);

  /**
   * Prefix increment operator.
   */
  CUDA_FUNC_BOTH VarCoord11& operator++() {
    inc();
    return *this;
  }
  
  /**
   * Postfix increment operator.
   */
  CUDA_FUNC_BOTH VarCoord11 operator++(int) {
    VarCoord11 tmp(*this);
    inc();
    return tmp;
  }
  
  /**
   * Prefix decrement operator.
   */
  CUDA_FUNC_BOTH VarCoord11& operator--() {
    dec();
    return *this;
  }
  
  /**
   * Postfix decrement operator.
   */
  CUDA_FUNC_BOTH VarCoord11 operator--(int) {
    VarCoord11 tmp(*this);
    dec();
    return tmp;
  }

  
  
  
};

inline VarCoord11::VarCoord11() {
}




inline VarCoord11::VarCoord11(const int ix) {
  setIndex(ix);
}


inline void VarCoord11::inc() {
  
  
}

inline void VarCoord11::dec() {
  
  
}

inline int VarCoord11::index() const {
  
  return 0;
  
}

inline void VarCoord11::setIndex(const int ix) {  
}

#endif
