





/**
 * @file
 *
 * @author Generated by LibBi
 * $Rev$
 * $Date$
 */
#ifndef LIBBI_VARCOORD0_HPP
#define LIBBI_VARCOORD0_HPP

/**
 * Coordinate: 0.
 */
class VarCoord0 {
public:
  /**
   * Default constructor.
   */
  CUDA_FUNC_BOTH VarCoord0();
  
  

  
  /**
   * Construct from serial index.
   *
   * @param ix Serial index.
   */
  CUDA_FUNC_BOTH VarCoord0(const int ix);
  
  
  /**
   * Increment to next coordinate in serial ordering.
   */
  CUDA_FUNC_BOTH void inc();
   
  /**
   * Decrement to previous coordinate in serial ordering.
   */
  CUDA_FUNC_BOTH void dec();

  /**
   * Recover serial index.
   * 
   * @return Serial index for coordinate.
   */
  CUDA_FUNC_BOTH int index() const;
  
  /**
   * Set serial index.
   *
   * @param ix Serial index for coordinate.
   *
   * Sets the coordinate to be equivalent to the given serial index.
   */
  CUDA_FUNC_BOTH void setIndex(const int ix);

  /**
   * Prefix increment operator.
   */
  CUDA_FUNC_BOTH VarCoord0& operator++() {
    inc();
    return *this;
  }
  
  /**
   * Postfix increment operator.
   */
  CUDA_FUNC_BOTH VarCoord0 operator++(int) {
    VarCoord0 tmp(*this);
    inc();
    return tmp;
  }
  
  /**
   * Prefix decrement operator.
   */
  CUDA_FUNC_BOTH VarCoord0& operator--() {
    dec();
    return *this;
  }
  
  /**
   * Postfix decrement operator.
   */
  CUDA_FUNC_BOTH VarCoord0 operator--(int) {
    VarCoord0 tmp(*this);
    dec();
    return tmp;
  }

  
  
  
};

inline VarCoord0::VarCoord0() {
}




inline VarCoord0::VarCoord0(const int ix) {
  setIndex(ix);
}


inline void VarCoord0::inc() {
  
  
}

inline void VarCoord0::dec() {
  
  
}

inline int VarCoord0::index() const {
  
  return 0;
  
}

inline void VarCoord0::setIndex(const int ix) {  
}

#endif
