





/**
 * @file
 *
 * @author Generated by LibBi
 * $Rev$
 * $Date$
 */
#ifndef LIBBI_VARCOORD3_HPP
#define LIBBI_VARCOORD3_HPP

/**
 * Coordinate: 3.
 */
class VarCoord3 {
public:
  /**
   * Default constructor.
   */
  CUDA_FUNC_BOTH VarCoord3();
  
  

  
  /**
   * Construct from serial index.
   *
   * @param ix Serial index.
   */
  CUDA_FUNC_BOTH VarCoord3(const int ix);
  
  
  /**
   * Increment to next coordinate in serial ordering.
   */
  CUDA_FUNC_BOTH void inc();
   
  /**
   * Decrement to previous coordinate in serial ordering.
   */
  CUDA_FUNC_BOTH void dec();

  /**
   * Recover serial index.
   * 
   * @return Serial index for coordinate.
   */
  CUDA_FUNC_BOTH int index() const;
  
  /**
   * Set serial index.
   *
   * @param ix Serial index for coordinate.
   *
   * Sets the coordinate to be equivalent to the given serial index.
   */
  CUDA_FUNC_BOTH void setIndex(const int ix);

  /**
   * Prefix increment operator.
   */
  CUDA_FUNC_BOTH VarCoord3& operator++() {
    inc();
    return *this;
  }
  
  /**
   * Postfix increment operator.
   */
  CUDA_FUNC_BOTH VarCoord3 operator++(int) {
    VarCoord3 tmp(*this);
    inc();
    return tmp;
  }
  
  /**
   * Prefix decrement operator.
   */
  CUDA_FUNC_BOTH VarCoord3& operator--() {
    dec();
    return *this;
  }
  
  /**
   * Postfix decrement operator.
   */
  CUDA_FUNC_BOTH VarCoord3 operator--(int) {
    VarCoord3 tmp(*this);
    dec();
    return tmp;
  }

  
  
  
};

inline VarCoord3::VarCoord3() {
}




inline VarCoord3::VarCoord3(const int ix) {
  setIndex(ix);
}


inline void VarCoord3::inc() {
  
  
}

inline void VarCoord3::dec() {
  
  
}

inline int VarCoord3::index() const {
  
  return 0;
  
}

inline void VarCoord3::setIndex(const int ix) {  
}

#endif
