
/**
 * @file
 *
 * @author Generated by LibBi
 * $Rev$
 * $Date$
 */
#include "ModelSIR.hpp"

using namespace bi;

ModelSIR::ModelSIR() : Model(*this) {
  /* add dimensions */

  /* add variables */
  addVar<ModelSIR,Var0>(var0);
  addVar<ModelSIR,Var1>(var1);
  addVar<ModelSIR,Var2>(var2);
  addVar<ModelSIR,Var3>(var3);
  addVar<ModelSIR,Var4>(var4);
  addVar<ModelSIR,Var5>(var5);
  addVar<ModelSIR,Var6>(var6);
}
