





/**
 * @file
 *
 * @author Generated by LibBi
 * $Rev$
 * $Date$
 */
#ifndef LIBBI_VARCOORD6_HPP
#define LIBBI_VARCOORD6_HPP

/**
 * Coordinate: 6.
 */
class VarCoord6 {
public:
  /**
   * Default constructor.
   */
  CUDA_FUNC_BOTH VarCoord6();
  
  

  
  /**
   * Construct from serial index.
   *
   * @param ix Serial index.
   */
  CUDA_FUNC_BOTH VarCoord6(const int ix);
  
  
  /**
   * Increment to next coordinate in serial ordering.
   */
  CUDA_FUNC_BOTH void inc();
   
  /**
   * Decrement to previous coordinate in serial ordering.
   */
  CUDA_FUNC_BOTH void dec();

  /**
   * Recover serial index.
   * 
   * @return Serial index for coordinate.
   */
  CUDA_FUNC_BOTH int index() const;
  
  /**
   * Set serial index.
   *
   * @param ix Serial index for coordinate.
   *
   * Sets the coordinate to be equivalent to the given serial index.
   */
  CUDA_FUNC_BOTH void setIndex(const int ix);

  /**
   * Prefix increment operator.
   */
  CUDA_FUNC_BOTH VarCoord6& operator++() {
    inc();
    return *this;
  }
  
  /**
   * Postfix increment operator.
   */
  CUDA_FUNC_BOTH VarCoord6 operator++(int) {
    VarCoord6 tmp(*this);
    inc();
    return tmp;
  }
  
  /**
   * Prefix decrement operator.
   */
  CUDA_FUNC_BOTH VarCoord6& operator--() {
    dec();
    return *this;
  }
  
  /**
   * Postfix decrement operator.
   */
  CUDA_FUNC_BOTH VarCoord6 operator--(int) {
    VarCoord6 tmp(*this);
    dec();
    return tmp;
  }

  
  
  
};

inline VarCoord6::VarCoord6() {
}




inline VarCoord6::VarCoord6(const int ix) {
  setIndex(ix);
}


inline void VarCoord6::inc() {
  
  
}

inline void VarCoord6::dec() {
  
  
}

inline int VarCoord6::index() const {
  
  return 0;
  
}

inline void VarCoord6::setIndex(const int ix) {  
}

#endif
