





/**
 * @file
 *
 * @author Generated by LibBi
 * $Rev$
 * $Date$
 */
#ifndef LIBBI_VARCOORD9_HPP
#define LIBBI_VARCOORD9_HPP

/**
 * Coordinate: 9.
 */
class VarCoord9 {
public:
  /**
   * Default constructor.
   */
  CUDA_FUNC_BOTH VarCoord9();
  
  

  
  /**
   * Construct from serial index.
   *
   * @param ix Serial index.
   */
  CUDA_FUNC_BOTH VarCoord9(const int ix);
  
  
  /**
   * Increment to next coordinate in serial ordering.
   */
  CUDA_FUNC_BOTH void inc();
   
  /**
   * Decrement to previous coordinate in serial ordering.
   */
  CUDA_FUNC_BOTH void dec();

  /**
   * Recover serial index.
   * 
   * @return Serial index for coordinate.
   */
  CUDA_FUNC_BOTH int index() const;
  
  /**
   * Set serial index.
   *
   * @param ix Serial index for coordinate.
   *
   * Sets the coordinate to be equivalent to the given serial index.
   */
  CUDA_FUNC_BOTH void setIndex(const int ix);

  /**
   * Prefix increment operator.
   */
  CUDA_FUNC_BOTH VarCoord9& operator++() {
    inc();
    return *this;
  }
  
  /**
   * Postfix increment operator.
   */
  CUDA_FUNC_BOTH VarCoord9 operator++(int) {
    VarCoord9 tmp(*this);
    inc();
    return tmp;
  }
  
  /**
   * Prefix decrement operator.
   */
  CUDA_FUNC_BOTH VarCoord9& operator--() {
    dec();
    return *this;
  }
  
  /**
   * Postfix decrement operator.
   */
  CUDA_FUNC_BOTH VarCoord9 operator--(int) {
    VarCoord9 tmp(*this);
    dec();
    return tmp;
  }

  
  
  
};

inline VarCoord9::VarCoord9() {
}




inline VarCoord9::VarCoord9(const int ix) {
  setIndex(ix);
}


inline void VarCoord9::inc() {
  
  
}

inline void VarCoord9::dec() {
  
  
}

inline int VarCoord9::index() const {
  
  return 0;
  
}

inline void VarCoord9::setIndex(const int ix) {  
}

#endif
