




/**
 * @file
 *
 * @author Generated by LibBi
 * $Rev$
 * $Date$
 */
#ifndef LIBBI_BLOCK5_HPP
#define LIBBI_BLOCK5_HPP


#include "bi/typelist/macro_typelist.hpp"
#include "bi/traits/block_traits.hpp"

#include "boost/typeof/typeof.hpp"

/**
 * Type list of sub-blocks.
 */
BEGIN_TYPELIST(Block5BlockTypeList)
END_TYPELIST()

/**
 * Block: parameter.
 */
class Block5 {
public:
  /**
   * Type list of sub-blocks.
   */
  typedef GET_TYPETREE(Block5BlockTypeList) block_typelist;
    
  
  
  template<bi::Location L>
  static void simulates(bi::State<ModelSIR,L>& s);
  

  
  
  template<bi::Location L>
  static void samples(bi::Random& rng, bi::State<ModelSIR,L>& s);
  

  
  
  template<bi::Location L, class V1>
  static void logDensities(bi::State<ModelSIR,L>& s, V1 lp);
  

  
  
  template<bi::Location L, class V1>
  static void maxLogDensities(bi::State<ModelSIR,L>& s, V1 lp);
  

};


  
  template<bi::Location L>
  void Block5::simulates(bi::State<ModelSIR,L>& s)
  
 {
}


  
  template<bi::Location L>
  void Block5::samples(bi::Random& rng, bi::State<ModelSIR,L>& s)
  
 {
}


  
  template<bi::Location L, class V1>
  void Block5::logDensities(bi::State<ModelSIR,L>& s, V1 lp)
  
 {
}


  
  template<bi::Location L, class V1>
  void Block5::maxLogDensities(bi::State<ModelSIR,L>& s, V1 lp)
  
 {
}


#endif
