






/**
 * @file
 *
 * @author Generated by LibBi
 * $Rev$
 * $Date$
 */
#ifndef LIBBI_BLOCK6_HPP
#define LIBBI_BLOCK6_HPP


#include "bi/typelist/macro_typelist.hpp"
#include "bi/traits/block_traits.hpp"

#include "boost/typeof/typeof.hpp"

/**
 * Type list of sub-blocks.
 */
BEGIN_TYPELIST(Block6BlockTypeList)
END_TYPELIST()

#include "bi/state/Mask.hpp"

/**
 * Block: bridge.
 */
class Block6 {
public:
  /**
   * Type list of sub-blocks.
   */
  typedef GET_TYPETREE(Block6BlockTypeList) block_typelist;

  
  
  template<bi::Location L>
  static void simulates(bi::State<ModelSIR,L>& s);
  

  
  
  template<bi::Location L>
  static void samples(bi::Random& rng, bi::State<ModelSIR,L>& s);
  

  
  
  template<bi::Location L, class V1>
  static void logDensities(bi::State<ModelSIR,L>& s, V1 lp);
  

  
  
  template<bi::Location L, class V1>
  static void maxLogDensities(bi::State<ModelSIR,L>& s, V1 lp);
  

  
  
  
  template<bi::Location L>
  static void simulates(bi::State<ModelSIR,L>& s, const bi::Mask<L>& mask);
  

  
  
  template<bi::Location L>
  static void samples(bi::Random& rng, bi::State<ModelSIR,L>& s, const bi::Mask<L>& mask);
  

  
  
  template<bi::Location L, class V1>
  static void logDensities(bi::State<ModelSIR,L>& s, const bi::Mask<L>& mask, V1 lp);
  

  
  
  template<bi::Location L, class V1>
  static void maxLogDensities(bi::State<ModelSIR,L>& s, const bi::Mask<L>& mask, V1 lp);
  

};


  
  template<bi::Location L>
  void Block6::simulates(bi::State<ModelSIR,L>& s)
  
 {
}


  
  template<bi::Location L>
  void Block6::samples(bi::Random& rng, bi::State<ModelSIR,L>& s)
  
 {
}


  
  template<bi::Location L, class V1>
  void Block6::logDensities(bi::State<ModelSIR,L>& s, V1 lp)
  
 {
}


  
  template<bi::Location L, class V1>
  void Block6::maxLogDensities(bi::State<ModelSIR,L>& s, V1 lp)
  
 {
}


  
  template<bi::Location L>
  void Block6::simulates(bi::State<ModelSIR,L>& s, const bi::Mask<L>& mask)
  
 {
}


  
  template<bi::Location L>
  void Block6::samples(bi::Random& rng, bi::State<ModelSIR,L>& s, const bi::Mask<L>& mask)
  
 {
}


  
  template<bi::Location L, class V1>
  void Block6::logDensities(bi::State<ModelSIR,L>& s, const bi::Mask<L>& mask, V1 lp)
  
 {
}


  
  template<bi::Location L, class V1>
  void Block6::maxLogDensities(bi::State<ModelSIR,L>& s, const bi::Mask<L>& mask, V1 lp)
  
 {
}


#endif

