







/**
 * @file
 *
 * @author Generated by LibBi
 * $Rev$
 * $Date$
 */
#ifndef LIBBI_BLOCK10_HPP
#define LIBBI_BLOCK10_HPP

#include "Block15.hpp"

#include "bi/typelist/macro_typelist.hpp"
#include "bi/traits/block_traits.hpp"

#include "boost/typeof/typeof.hpp"

/**
 * Type list of sub-blocks.
 */
BEGIN_TYPELIST(Block10BlockTypeList)
SINGLE_TYPE(1, Block15)
END_TYPELIST()

/**
 * Block: proposal_initial.
 */
class Block10 {
public:
  /**
   * Type list of sub-blocks.
   */
  typedef GET_TYPETREE(Block10BlockTypeList) block_typelist;
    
  
  
  template<bi::Location L>
  static void simulates(bi::State<ModelSIR,L>& s);
  

  
  
  template<bi::Location L>
  static void samples(bi::Random& rng, bi::State<ModelSIR,L>& s);
  

  
  
  template<bi::Location L, class V1>
  static void logDensities(bi::State<ModelSIR,L>& s, V1 lp);
  

  
  
  template<bi::Location L, class V1>
  static void maxLogDensities(bi::State<ModelSIR,L>& s, V1 lp);
  

};


  
  template<bi::Location L>
  void Block10::simulates(bi::State<ModelSIR,L>& s)
  
 {
  Block15::simulates(s);
}


  
  template<bi::Location L>
  void Block10::samples(bi::Random& rng, bi::State<ModelSIR,L>& s)
  
 {
  Block15::samples(rng, s);
}


  
  template<bi::Location L, class V1>
  void Block10::logDensities(bi::State<ModelSIR,L>& s, V1 lp)
  
 {
  Block15::logDensities(s, lp);
}


  
  template<bi::Location L, class V1>
  void Block10::maxLogDensities(bi::State<ModelSIR,L>& s, V1 lp)
  
 {
  Block15::maxLogDensities(s, lp);
}


#endif

