





/**
 * @file
 *
 * @author Generated by LibBi
 * $Rev$
 * $Date$
 */
#ifndef LIBBI_BLOCK1_HPP
#define LIBBI_BLOCK1_HPP

#include "Block12.hpp"

#include "bi/typelist/macro_typelist.hpp"
#include "bi/traits/block_traits.hpp"

#include "boost/typeof/typeof.hpp"

/**
 * Type list of sub-blocks.
 */
BEGIN_TYPELIST(Block1BlockTypeList)
SINGLE_TYPE(1, Block12)
END_TYPELIST()

/**
 * Block: initial.
 */
class Block1 {
public:
  /**
   * Type list of sub-blocks.
   */
  typedef GET_TYPETREE(Block1BlockTypeList) block_typelist;
    
  
  
  template<bi::Location L>
  static void simulates(bi::State<ModelSIR,L>& s);
  

  
  
  template<bi::Location L>
  static void samples(bi::Random& rng, bi::State<ModelSIR,L>& s);
  

  
  
  template<bi::Location L, class V1>
  static void logDensities(bi::State<ModelSIR,L>& s, V1 lp);
  

  
  
  template<bi::Location L, class V1>
  static void maxLogDensities(bi::State<ModelSIR,L>& s, V1 lp);
  

};


  
  template<bi::Location L>
  void Block1::simulates(bi::State<ModelSIR,L>& s)
  
 {
  Block12::simulates(s);
}


  
  template<bi::Location L>
  void Block1::samples(bi::Random& rng, bi::State<ModelSIR,L>& s)
  
 {
  Block12::samples(rng, s);
}


  
  template<bi::Location L, class V1>
  void Block1::logDensities(bi::State<ModelSIR,L>& s, V1 lp)
  
 {
  Block12::logDensities(s, lp);
}


  
  template<bi::Location L, class V1>
  void Block1::maxLogDensities(bi::State<ModelSIR,L>& s, V1 lp)
  
 {
  Block12::maxLogDensities(s, lp);
}


#endif
