







/**
 * @file
 *
 * @author Generated by LibBi
 * $Rev$
 * $Date$
 */
#ifndef LIBBI_BLOCK6_HPP
#define LIBBI_BLOCK6_HPP

#include "Block19.hpp"

#include "bi/typelist/macro_typelist.hpp"
#include "bi/traits/block_traits.hpp"

#include "boost/typeof/typeof.hpp"

/**
 * Type list of sub-blocks.
 */
BEGIN_TYPELIST(Block6BlockTypeList)
SINGLE_TYPE(1, Block19)
END_TYPELIST()

/**
 * Block: proposal_initial.
 */
class Block6 {
public:
  /**
   * Type list of sub-blocks.
   */
  typedef GET_TYPETREE(Block6BlockTypeList) block_typelist;
    
  
  
  template<bi::Location L>
  static void simulates(bi::State<ModelSIR,L>& s);
  

  
  
  template<bi::Location L>
  static void samples(bi::Random& rng, bi::State<ModelSIR,L>& s);
  

  
  
  template<bi::Location L, class V1>
  static void logDensities(bi::State<ModelSIR,L>& s, V1 lp);
  

  
  
  template<bi::Location L, class V1>
  static void maxLogDensities(bi::State<ModelSIR,L>& s, V1 lp);
  

};


  
  template<bi::Location L>
  void Block6::simulates(bi::State<ModelSIR,L>& s)
  
 {
  Block19::simulates(s);
}


  
  template<bi::Location L>
  void Block6::samples(bi::Random& rng, bi::State<ModelSIR,L>& s)
  
 {
  Block19::samples(rng, s);
}


  
  template<bi::Location L, class V1>
  void Block6::logDensities(bi::State<ModelSIR,L>& s, V1 lp)
  
 {
  Block19::logDensities(s, lp);
}


  
  template<bi::Location L, class V1>
  void Block6::maxLogDensities(bi::State<ModelSIR,L>& s, V1 lp)
  
 {
  Block19::maxLogDensities(s, lp);
}


#endif

