




/**
 * @file
 *
 * @author Generated by LibBi
 * $Rev$
 * $Date$
 */
#ifndef LIBBI_BLOCK5_HPP
#define LIBBI_BLOCK5_HPP

#include "Block18.hpp"

#include "bi/typelist/macro_typelist.hpp"
#include "bi/traits/block_traits.hpp"

#include "boost/typeof/typeof.hpp"

/**
 * Type list of sub-blocks.
 */
BEGIN_TYPELIST(Block5BlockTypeList)
SINGLE_TYPE(1, Block18)
END_TYPELIST()

#include "bi/state/Mask.hpp"

/**
 * Block: observation.
 */
class Block5 {
public:
  /**
   * Type list of sub-blocks.
   */
  typedef GET_TYPETREE(Block5BlockTypeList) block_typelist;

  
  
  template<bi::Location L>
  static void simulates(bi::State<ModelSIR,L>& s);
  

  
  
  template<bi::Location L>
  static void samples(bi::Random& rng, bi::State<ModelSIR,L>& s);
  

  
  
  template<bi::Location L, class V1>
  static void logDensities(bi::State<ModelSIR,L>& s, V1 lp);
  

  
  
  template<bi::Location L, class V1>
  static void maxLogDensities(bi::State<ModelSIR,L>& s, V1 lp);
  

  
  
  
  template<bi::Location L>
  static void simulates(bi::State<ModelSIR,L>& s, const bi::Mask<L>& mask);
  

  
  
  template<bi::Location L>
  static void samples(bi::Random& rng, bi::State<ModelSIR,L>& s, const bi::Mask<L>& mask);
  

  
  
  template<bi::Location L, class V1>
  static void logDensities(bi::State<ModelSIR,L>& s, const bi::Mask<L>& mask, V1 lp);
  

  
  
  template<bi::Location L, class V1>
  static void maxLogDensities(bi::State<ModelSIR,L>& s, const bi::Mask<L>& mask, V1 lp);
  

};


  
  template<bi::Location L>
  void Block5::simulates(bi::State<ModelSIR,L>& s)
  
 {
  Block18::simulates(s);
}


  
  template<bi::Location L>
  void Block5::samples(bi::Random& rng, bi::State<ModelSIR,L>& s)
  
 {
  Block18::samples(rng, s);
}


  
  template<bi::Location L, class V1>
  void Block5::logDensities(bi::State<ModelSIR,L>& s, V1 lp)
  
 {
  Block18::logDensities(s, lp);
}


  
  template<bi::Location L, class V1>
  void Block5::maxLogDensities(bi::State<ModelSIR,L>& s, V1 lp)
  
 {
  Block18::maxLogDensities(s, lp);
}


  
  template<bi::Location L>
  void Block5::simulates(bi::State<ModelSIR,L>& s, const bi::Mask<L>& mask)
  
 {
  Block18::simulates(s, mask);
}


  
  template<bi::Location L>
  void Block5::samples(bi::Random& rng, bi::State<ModelSIR,L>& s, const bi::Mask<L>& mask)
  
 {
  Block18::samples(rng, s, mask);
}


  
  template<bi::Location L, class V1>
  void Block5::logDensities(bi::State<ModelSIR,L>& s, const bi::Mask<L>& mask, V1 lp)
  
 {
  Block18::logDensities(s, mask, lp);
}


  
  template<bi::Location L, class V1>
  void Block5::maxLogDensities(bi::State<ModelSIR,L>& s, const bi::Mask<L>& mask, V1 lp)
  
 {
  Block18::maxLogDensities(s, mask, lp);
}


#endif
