







/**
 * @file
 *
 * @author Generated by LibBi
 * $Rev$
 * $Date$
 */
#ifndef LIBBI_BLOCK10_HPP
#define LIBBI_BLOCK10_HPP

#include "Block23.hpp"
#include "Block24.hpp"
#include "Block25.hpp"
#include "Block11.hpp"

#include "bi/typelist/macro_typelist.hpp"
#include "bi/traits/block_traits.hpp"

#include "boost/typeof/typeof.hpp"


/**
 * Type list of sub-blocks.
 */
BEGIN_TYPELIST(Block10BlockTypeList)
SINGLE_TYPE(1, Block23)
SINGLE_TYPE(1, Block24)
SINGLE_TYPE(1, Block25)
SINGLE_TYPE(1, Block11)
END_TYPELIST()

/**
 * Block: lookahead_transition.
 */
class Block10 {
public:
  /**
   * Type list of sub-blocks.
   */
  typedef GET_TYPETREE(Block10BlockTypeList) block_typelist;

  
  
  template<class T1, bi::Location L>
  static void simulates(const T1 t1, const T1 t2, const bool onDelta, bi::State<ModelSIR,L>& s);
  

  
  
  template<class T1, bi::Location L>
  static void samples(bi::Random& rng, const T1 t1, const T1 t2, const bool onDelta, bi::State<ModelSIR,L>& s);
  

  
  
  template<class T1, bi::Location L, class V1>
  static void logDensities(const T1 t1, const T1 t2, const bool onDelta, bi::State<ModelSIR,L>& s, V1 lp);
  

  
  
  template<class T1, bi::Location L, class V1>
  static void maxLogDensities(const T1 t1, const T1 t2, const bool onDelta, bi::State<ModelSIR,L>& s, V1 lp);
  

  
  /**
   * Time step.
   */
  static real getDelta();
};


inline real Block10::getDelta() {
  return 1;
}


  
  template<class T1, bi::Location L>
  void Block10::simulates(const T1 t1, const T1 t2, const bool onDelta, bi::State<ModelSIR,L>& s)
  
 {
  Block23::simulates(t1, t2, onDelta, s);
  Block24::simulates(t1, t2, onDelta, s);
  Block25::simulates(t1, t2, onDelta, s);
  Block11::simulates(t1, t2, onDelta, s);
}


  
  template<class T1, bi::Location L>
  void Block10::samples(bi::Random& rng, const T1 t1, const T1 t2, const bool onDelta, bi::State<ModelSIR,L>& s)
  
 {
  Block23::samples(rng, t1, t2, onDelta, s);
  Block24::samples(rng, t1, t2, onDelta, s);
  Block25::samples(rng, t1, t2, onDelta, s);
  Block11::samples(rng, t1, t2, onDelta, s);
}


  
  template<class T1, bi::Location L, class V1>
  void Block10::logDensities(const T1 t1, const T1 t2, const bool onDelta, bi::State<ModelSIR,L>& s, V1 lp)
  
 {
  Block23::logDensities(t1, t2, onDelta, s);
  Block24::logDensities(t1, t2, onDelta, s);
  Block25::logDensities(t1, t2, onDelta, s);
  Block11::logDensities(t1, t2, onDelta, s);
}


  
  template<class T1, bi::Location L, class V1>
  void Block10::maxLogDensities(const T1 t1, const T1 t2, const bool onDelta, bi::State<ModelSIR,L>& s, V1 lp)
  
 {
  Block23::maxLogDensities(t1, t2, onDelta, s);
  Block24::maxLogDensities(t1, t2, onDelta, s);
  Block25::maxLogDensities(t1, t2, onDelta, s);
  Block11::maxLogDensities(t1, t2, onDelta, s);
}
 


#endif


